version: '3'
services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=xai@123
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./pg_vector_db:/var/lib/postgresql/data   # Local folder for database persistence
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # Initial script if needed